In [1]:
import cv2
from matplotlib import pyplot as plt
import numpy as np
import utils
from scipy.spatial.distance import pdist, squareform
from tsp_solver.greedy_numpy import solve_tsp
from math import sqrt


Cell below is for image reformating

In [2]:
img = cv2.imread('./Images/statue.jpg', 1)
#imgCont = utils.contrast(img)
imgresize = utils.rez(img)
imgGray = cv2.cvtColor(imgresize, cv2.COLOR_BGR2GRAY)
imgDither = utils.dithering(imgGray, .2)
dPoints = np.argwhere(imgDither == 0)
dPoints = np.delete(dPoints, 2, 1)
print(dPoints.shape)
#print(dPoints[:3])




(129072, 2)


In [3]:
dPoints = dPoints[:13000]
tour = utils.nearest_neighbor_it(dPoints)
print(tour)

None


In [ ]:
final = np.hsplit(tour, 2)
Points = utils.scale(final, 2)
plt.plot(Points[0], Points[1], c = 'k', linewidth = .2)
plt.show()

In [ ]:
cv2.imshow('orig', img)
#cv2.imshow('Contrast', imgCont)
#cv2.imshow('resize', imgresize)
cv2.imshow('Gray Scale', imgGray)
cv2.imshow('Dither', imgDither)

cv2.waitKey(0)

In [ ]:
test = dPoints[:10]
tour = np.zeros((1, 2))
while test.size > 0:
    current = tour[-1]
    nearest_city = None
    nearest_dist = float('inf')
    for i in range(len(test)):
        if np.array_equal(test[i], current):
            continue
        distance = np.linalg.norm(current - test[i])
        if distance < nearest_dist:
            nearest_city = i
            nearest_dist = distance
    tour = np.append(tour, [test[nearest_city]], axis=0)
    location = np.where(test == tour[-1])
    test = np.delete(test, location[0][0], 0)
print(tour)
    




In [6]:
temp = np.random.rand(5, 2)
print(temp)
temp[:,0] *= 50
temp[:,1] *= 100

print(temp)
temp = np.round(temp)
print(temp)



[[0.63220435 0.92101855]
 [0.97473815 0.45481756]
 [0.41242339 0.00452975]
 [0.10889827 0.65486311]
 [0.29325684 0.77837623]]
[[31.61021735 92.10185507]
 [48.73690762 45.4817561 ]
 [20.62116968  0.4529748 ]
 [ 5.44491362 65.48631131]
 [14.66284211 77.83762282]]
[[32. 92.]
 [49. 45.]
 [21.  0.]
 [ 5. 65.]
 [15. 78.]]


In [11]:
myArray = np.array([3,3])
print(myArray)
myArray2 = np.array([[2,1],[3,2],[5,3]])
print(myArray2)
for i in myArray2:
    print(i)

[3 3]
[[2 1]
 [3 2]
 [5 3]]
[2 1]
[3 2]
[5 3]
