In [ ]:
import cv2
from matplotlib import pyplot as plt
import numpy as np
import utils


In [ ]:
img = cv2.imread('./Images/statue.jpg', 1)
imgresize = utils.rez(img)
imgGray = cv2.cvtColor(imgresize, cv2.COLOR_BGR2GRAY)
imgDither = utils.dithering(imgGray)

In [ ]:
black_points = np.argwhere(imgDither == 0)


In [13]:
print(black_points[80:150])


[[  1  74   0]
 [  1  75   0]
 [  1  77   0]
 [  1  78   0]
 [  1  80   0]
 [  1  81   0]
 [  1  83   0]
 [  1  85   0]
 [  1  87   0]
 [  1  88   0]
 [  1  90   0]
 [  1  92   0]
 [  1  93   0]
 [  1  94   0]
 [  1  96   0]
 [  1  98   0]
 [  1 100   0]
 [  1 102   0]
 [  1 104   0]
 [  1 106   0]
 [  1 108   0]
 [  1 110   0]
 [  1 112   0]
 [  1 114   0]
 [  1 116   0]
 [  1 118   0]
 [  1 120   0]
 [  1 122   0]
 [  1 124   0]
 [  1 126   0]]


In [ ]:
ID = utils.pointConversion(imgDither)
final =  #utils.order(ID) this function does not work how I want
final = np.hsplit(final, 2)
Points = utils.scale(final, 2)

In [ ]:
plt.subplot(1, 2, 1)
plt.plot(final[0], final[1], '.')
plt.title('Dither Image')


plt.subplot(1, 2, 2)
plt.plot(Points[0], Points[1], '.')
plt.title('Scaled Image')

cv2.imshow('Original', img)
cv2.imshow('resize', imgresize)
cv2.imshow('Gray', imgGray)
cv2.imshow('Dith', imgDither)

plt.show()
cv2.waitKey(0)

In [ ]:
plt.plot(Points[0], Points[1], c = 'k', linewidth = .2)
plt.show()
cv2.waitKey(0)